# Generated by Django 4.2.20 on 2025-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('payment', models.CharField(max_length=100)),
                ('agree', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
